spring.application.name=backend



###Mongo Db connection###
###Mongo Db connection###
spring.mongodb.uri=mongodb+srv://admin-shrey:pNOycPLFDJ81be23@cluster0.hovzbpz.mongodb.net/eBookDB?retryWrites=true&w=majority&tls=true
spring.mongodb.database=eBookDB



spring.security.user.name=admin
spring.security.user.password={noop}admin123

spring.security.user.roles=USER


spring.servlet.multipart.max-file-size=2GB
spring.servlet.multipart.max-request-size=2GB

server.tomcat.max-swallow-size=-1


