spring.application.name=backend



###Mongo Db connection###
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=ardentBookStore



###AWS Configuration###

aws.s3.region=eu-north-1
aws.s3.bucketName=amzn-s3-book-img
aws.s3.accessKey=AKIASZMFALWIQZFBUCP2
aws.s3.secretKey=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
